[package]
name = "mark_os"
version = "0.1.0"
edition = "2018"
authors = ["Mark <mark@gandolfo.com.au>"]

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
